# This file was generated by GoReleaser. DO NOT EDIT.
cask "remoteok-cli" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "d9d686ae473148b34478fe54c7cd56ac62c4164056c4a4b1fbfa3c5ba8980afe"
      url "https://github.com/jjuanrivvera/remoteok-cli/releases/download/v#{version}/remoteok-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b51fcc2c0917ff364d0ca82a89ee03773b28fd7462bdce1b6bc683955a01ff40"
      url "https://github.com/jjuanrivvera/remoteok-cli/releases/download/v#{version}/remoteok-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "29def61952d6efad4981f00c8f5583fe6154f00c4180ca1d7704b8e60f38dca7"
      url "https://github.com/jjuanrivvera/remoteok-cli/releases/download/v#{version}/remoteok-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "34b27bf8917b9cd755821df8815c370f7e3136937eca4d1218cbbeaa9b5bc3c3"
      url "https://github.com/jjuanrivvera/remoteok-cli/releases/download/v#{version}/remoteok-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "remoteok-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/remoteok-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remoteok"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/remoteok"]
  end

  # No zap stanza required
end
