# This file was generated by GoReleaser. DO NOT EDIT.
cask "remoteok-cli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "7dfbd3be6588331aca04db097602002a853b13dc3665a1a320bc19f1360fb06d"
      url "https://github.com/jjuanrivvera/remoteok-cli/releases/download/v#{version}/remoteok-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "90c9b894f8e2e6d50d8b294302cab2fc79806acacc9a521b98595ff1e8fc83fd"
      url "https://github.com/jjuanrivvera/remoteok-cli/releases/download/v#{version}/remoteok-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "29eef72b59fd689c9f2af4801b017cc413ee3edc4ca70eaaf462d48752fcf377"
      url "https://github.com/jjuanrivvera/remoteok-cli/releases/download/v#{version}/remoteok-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "735af4e1818e2925f1e36692702317095b3b72400c3a520381437e02fbcf1af9"
      url "https://github.com/jjuanrivvera/remoteok-cli/releases/download/v#{version}/remoteok-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "remoteok-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/remoteok-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remoteok"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/remoteok"]
  end

  # No zap stanza required

end
