# This file was generated by GoReleaser. DO NOT EDIT.
cask "remoteok-cli" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "b531b61ec392b616434c83ac8fb757fa1d2bec05851c23d6981f2230fdc1a220"
      url "https://github.com/jjuanrivvera/remoteok-cli/releases/download/v#{version}/remoteok-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "667d75dfa50a8617d3225b77924cb9817f7002a5c05cc1cabbd89af11dc6d811"
      url "https://github.com/jjuanrivvera/remoteok-cli/releases/download/v#{version}/remoteok-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c94b81e3ca37b47ef99a683255b05eaa8d04f26e2034ba35e9a8c831e05e23ef"
      url "https://github.com/jjuanrivvera/remoteok-cli/releases/download/v#{version}/remoteok-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "54eb0500b9775be4d0a0c2d8aaa2c15cea5ccbfd3ffd07a665f9e6ebbbeb4868"
      url "https://github.com/jjuanrivvera/remoteok-cli/releases/download/v#{version}/remoteok-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "remoteok-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/remoteok-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remoteok"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/remoteok"]
  end

  # No zap stanza required

end
